### PR TITLE
Remove dashes from web app setting name

### LINKED ISSUE #2: Update example as web setting name does not work
https://github.com/CompositionalIT/storage-identity/blob/9570b6aad016ce922fe55b3b9c62f9a54368a447/infrastructure/Program.fs#L18

By the looks of it "storage-account-name" cannot be used as a setting key. Possibly it is because of the dashes but haven't looked further into it. I have successfully used StorageAccountName in a project.

### PR DESCRIPTION
**Pull request by theprash**
* Switch to Windows as a default (only because of the limit of one free Linux app service per region)
* Remove the dashes from the setting name anyway, in case anyone wants to deploy to Linux
* Changed `add_blob_container` to `add_private_container` to avoid another ARM deploy error. Presumably it was suggesting it doesn't make sense to grant identity access to a public container.

Closes #2

### CODE REVIEW

**Comment by isaacabraham** [comment]
You're not granting identity access to a public container, you're granting it to the storage account itself. It's perfectly reasonable to have a public container as well as a private one in a storage account I think?

**Comment by isaacabraham** [comment]
What ARM error were you getting on the deploy?

File: infrastructure/Program.fs [hunk 1]
```diff
@@ -15,14 +15,15 @@ let rg = $"{baseName}-rg"
...
+    operating_system OS.Windows
+    setting "StorageAccountName" storageAccountName
     zip_deploy "../publish"
     run_from_package
 }
 
 let storage = storageAccount {
     name storageAccountName
-    add_blob_container "data"
+    add_private_container "data"
```
Comment (isaacabraham) [inline infrastructure/Program.fs:26]: What error were you getting that necessitated this change - and did it definitely fix it?

File: infrastructure/Program.fs [hunk 2]
```diff
@@ -15,14 +15,15 @@ let rg = $"{baseName}-rg"
 let myWeb = webApp {
     name webAppName
     system_identity
-    setting "storage-account-name" storageAccountName
+    operating_system OS.Windows
+    setting "StorageAccountName" storageAccountName
```
Comment (isaacabraham) [inline infrastructure/Program.fs:19]: What's the standard for this if not `-` - is it perhaps snake case (e.g. `storage_account_name`?

Comment (theprash) [reply infrastructure/Program.fs:19]: I've almost always seen it as PascalCase in .NET land. And often they're mapped directly to objects with PascalCase properties so that makes sense to me. It's the casing I always use.

File: infrastructure/Program.fs (hunk 1 above)
Comment (theprash) [reply infrastructure/Program.fs:26]: This was the ARM error: `\"code\": \"PublicAccessNotPermitted\",\r\n    \"message\": \"Public access is not permitted on this storage account`.

Switching to a private container does indeed fix it.

Comment (theprash) [reply infrastructure/Program.fs:26]: Note: This was because the storage account itself has blob anonymous access disabled. Perhaps a default changed in Famer or ARM. In any case, it makes more sense for this demo for it to be a private container.
